# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Tilia Translations di Angela Brisotto
email: angela@tiliatranslations.it
author: Angela Brisotto
description: I have been helping individuals and organisations convey their words and ideas to a public that speaks a different language since 2019. Combining analysis, accuracy and wordsmithery, I translate texts from Polish and English into Italian, localise websites for the Italian market, revise translations and proofread texts written in Italian, including academic articles, and transcribe audio and video materials into Italian.

copyright: 'Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
<br>
<br>
TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
P.IVA/VAT: 05247030264
<br>
<br>
<br>
Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.'

credits: '&#9993; angela@tiliatranslations.it
<br>
<br>
Poniedziałek - Piątek: 9.00 - 17.00 (CET)
<br>
<a href="https://www.proz.com/translator/2997713">Mój kalendarz</a>'



# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
