# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Tilia Translations
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Buduję mosty łączące język angielski i polski z językiem włoskim. Wykorzystując swoje umiejętności analityczne, precyzję i sztukę władania słowem, oferuję tłumaczenie tekstów, lokalizację stron internetowych, weryfikację tłumaczeń i korektę tekstów i transkrypcję nagrań audio i wideo. Witam!

copyright: 'TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
VAT: 05247030264
<br>
31027, Spresiano (TV)
<br>
Włochy
<br>
<br>
Copyright &copy; 2022 Tilia Translations di Angela Brisotto. All Rights Reserved.
Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.
<br>
<br>'

credits: |
  JAK SIĘ ZE MNĄ SKONTAKTOWAĆ
  <br>
  <br>
  Jeśli chcesz się ze mną skontaktować w celu oceny możliwości współpracy, proszę napisać do mnie e-mail ze wszystkimi szczegółami zapytania. Odpowiem na Twoją wiadomość w ciągu 24 godzin w godzinach mojej pracy, tj. od poniedziałku do czwartku w godzinach 9:00 - 16:00 (czas środkowoeuropejski). 
  <br>
  <br>
  Wyślij <a href="mailto:angela@tiliatranslations.it">e-mail</a> do Angeli Brisotto: angela@tiliatranslations.it


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
