# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Angela Brisotto, Magister (MA) | Tilia Translations
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Nazywam się Angela Brisotto i buduję mosty łączące język angielski i polski z językiem włoskim. Wykorzystując swoje umiejętności analityczne, precyzję i sztukę władania słowem, oferuję tłumaczenie tekstów, lokalizację stron internetowych, weryfikację tłumaczeń i korektę tekstów i transkrypcję nagrań audio i wideo. Witam na mojej stronie internetowej!

copyright: 'TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
VAT: 05247030264
<br>
<br>
Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.
<br>
<br>'

credits: 'Notka na temat maili:
<br>
<br>
Odpowiadam tylko na maile z pytaniami biznesowymi.
<br>
Kiedy odpowiem na twój mail? Od poniedziałku do czwartku w godzinach 9.00 - 16.00 (CET).
<br>
Dziękuję za uwagę. &#127861;
<br>
To mój adres: <a href="mailto:angela@tiliatranslations.it">angela@tiliatranslations.it</a>'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
