# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Angela Brisotto, Magister (MA) | Tilia Translations
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Nazywam się Angela Brisotto i buduję mosty łączące język angielski i polski z językiem włoskim. Wykorzystując swoje umiejętności analityczne, precyzję i sztukę władania słowem, oferuję tłumaczenie tekstów, lokalizację stron internetowych, weryfikację tłumaczeń i korektę tekstów i transkrypcję nagrań audio i wideo. Witam na mojej stronie internetowej!

copyright: 'Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
<br>
<br>
TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
VAT: 05247030264
<br>
<br>
<br>
Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.'

credits: '&#9993; angela@tiliatranslations.it
<br>
<br>
Kiedy mogę się z Tobą skontaktować mailowo? 
<br>
Jestem dostępna od poniedziałku do czwartku w godzinach 9.00 - 16.00 (CET).
<br>
<br>
<a href="https://www.proz.com/translator/2997713">Mój kalendarz</a>'



# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: instagram
    url: https://www.instagram.com/tiliatranslationsangela/
